# Generated by Django 4.0.3 on 2022-04-10 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='sum',
            field=models.TextField(default='hhhhhh'),
        ),
    ]
