# Generated by Django 4.0.3 on 2022-04-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_products_sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='img',
            field=models.ImageField(default='imgs/1.jpg', upload_to='imgs/'),
        ),
    ]
