# Generated by Django 4.0.3 on 2022-04-17 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_products_name_alter_products_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='desc',
        ),
    ]
