# Generated by Django 4.0.3 on 2022-04-22 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_ordermodel_adressecl'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='ispayed',
            field=models.BooleanField(default=False),
        ),
    ]
