# Generated by Django 4.0.3 on 2022-04-25 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_ordermodel_ispayed'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='isshiped',
            field=models.BooleanField(default=False),
        ),
    ]
