# Generated by Django 4.0.3 on 2022-05-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_ordermodel_isshiped'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commented_on', models.DateTimeField(auto_now_add=True)),
                ('fname', models.CharField(blank=True, max_length=50)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=5)),
                ('gender', models.CharField(blank=True, max_length=50)),
                ('comment', models.CharField(blank=True, max_length=1000)),
            ],
        ),
    ]
